### ISSUE TITLE
How would I go about converting this to HDRP?

### ISSUE THREAD

**Issue by Nokdef** [Cyanilux/URP_GrassGeometryShader#1]
Hello! I'm trying to make a shader similar to this on HDRP,[ I already have a WIP of that, but I'm also struggling there. ](https://forum.unity.com/threads/converting-urp-shader-to-hdrp.998848/)

Would this be possible to be translated to HDRP or does it use URP-Specific features?

**Comment by Cyanilux** [comment]
Sorry, I'm not familiar with HDRP shaders so wouldn't know how difficult it would be to translate it. Geometry shaders also aren't the most performant things from what I understand so I think they tend to be avoided. I know I've also seen GPU instanced grass approaches too, (e.g. using [Graphics.DrawMeshInstancedIndirect](https://docs.unity3d.com/ScriptReference/Graphics.DrawMeshInstancedIndirect.html) though I'm not familiar with the exact setup).

Also while searching for HDRP specifically, I saw that there's a grass example here for Visual Effect Graph (sample #04) which might be useful : https://blogs.unity3d.com/2019/03/06/visual-effect-graph-samples/

**Comment by Nokdef** [comment]
Interesting! I was thinking of using the visual effect graph solution as well but wanted to keep it shader-based so I could use it more procedurally.

Anyhow, I'll keep looking around for solutions on a shader level, at any rate, thanks for answering :D
