### ISSUE TITLE
How do I modify the culling distance of "Toggle blade detail based on camera"=

### ISSUE THREAD

**Issue by ZayNepz** [Cyanilux/URP_GrassGeometryShader#5]

**Comment by Cyanilux** [comment]
Line 131 in Grass.hlsl should be responsible for the culling distance. It has hardcoded values, can change them or add properties to control it from material.

https://github.com/Cyanilux/URP_GrassGeometryShader/blob/51364f64bafda290f93fd87fdd7a334a62d3b877/GrassGeometry/Grass.hlsl#L131

**Comment by ZayNepz** [comment]
> Line 131 in Grass.hlsl should be responsible for the culling distance. It has hardcoded values, can change them or add properties to control it from material.
> 
> https://github.com/Cyanilux/URP_GrassGeometryShader/blob/51364f64bafda290f93fd87fdd7a334a62d3b877/GrassGeometry/Grass.hlsl#L131

Ah thanks!

Another quick q, is there a way to stop the grass from "refreshing" when moving or rotating the object? Every grass piecr changes place and orientation when moved. I feel it has to do with the positionWS and I could try mofiying it to local space maybe.
