### ISSUE TITLE
Mobile question

### ISSUE THREAD

**Issue by KillTheProcess23** [Cyanilux/URP_GrassGeometryShader#6]
Any way to make this optimized for mobile devices? It runs but the framerate drops drastically

**Comment by Cyanilux** [comment]
Likely not. Geometry shaders are pretty slow in general - they are mostly replaced by compute shaders, assuming your target platform can support those.

I know NedMakesGames has some tutorials on the various methods of rendering grass - https://www.youtube.com/playlist?list=PLAUha41PUKAaCr_ExiPJtpDHmAK6H7Ss9 (somewhat ignoring 2 and 3 which are still geometry shaders)

May also be other methods involving Graphics.DrawMeshInstancedIndirect (or newer equivalents) e.g. https://github.com/ColinLeung-NiloCat/UnityURP-MobileDrawMeshInstancedIndirectExample

Joyce / MinionsArt's has also shared a grass system - https://www.patreon.com/posts/grass-system-urp-83683483
